### ISSUE TITLE
Interpreted files should have shebangs.

### ISSUE THREAD

**Issue by TheBinaryFox** [mubaris/yes#32]
A lot of the interpreted files are missing [shebangs](https://en.wikipedia.org/wiki/Shebang_(Unix)).

To name a few:

- yes.php
- yes.py
- yes.swift

**Comment by jrgoldfinemiddleton** [comment]
I see that someone has already taken care of `yes.py`, but I've submitted a [PR](https://github.com/mubaris/yes/pull/43) for `yes.php` and `yes.swift`.

**Comment by mubaris** [comment]
I have taken care of remaining files. Thank you. :+1:
