### ISSUE TITLE
Implement 'yes' in BASIC

### ISSUE THREAD

**Issue by TheBinaryFox** [mubaris/yes#36]

**Comment by RobertZenz** [comment]
Which one?

**Comment by TheBinaryFox** [comment]
Any flavor except VB (that'll be added separately). Whatever can be compiled or interpreted on Mac/Linux?

**Comment by zvonimirr** [comment]
I implemented it in FreeBASIC. I'll make a Pascal version too,then commit

**Comment by mubaris** [comment]
Thanks! :+1:
