### ISSUE TITLE
BUILD_LASTEXIT is not cleared

### ISSUE THREAD

**Issue by mewa** [mubaris/yes#81]
When calling `BUILD-FAIL`, the `BUILD_LASTEXIT` variable is being set. However it is only cleared in `BUILT` and changed in `BUILD-RUN`. 

This leads to a scenario where if after calling `BUILD-FAIL` the next language is missing a compiler this will not be indicated. It also messes the layout of the messages printed.

Example:
1. Erlang fails with `BUILD-FAIL "TODO BUILD SCRIPT"`.
2. I don't have `fish` so `case` is not matched - it skips to `BUILD-END` 
3. Because `BUILD-LASTEXIT` is still set to  `"FAIL"` it exits without printing anything.
```
BUILD-END() {
	# Fail command.
	if [ "${BUILD_LASTEXIT}" = "FAIL" ]; then
		return 0;
	fi
...
```

**Comment by anbenson** [comment]
Was this fixed? Should it be closed?

**Comment by mubaris** [comment]
Sorry, It's closed.
